config/routes.rb
Rails.application.routes.draw do
  get 'news/index'
  get 'welcome/contact_us'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    def index 
        @news = News.all
    end
end

app/controllers/welcome_controller.rb
require 'open-uri'
require 'nokogiri'
require 'rubygems'
class WelcomeController < ApplicationController
  def index
    @news = News.all
    parse_posts
  end
  def contact_us
  end
  def parse_posts
    url = 'http://hot-rock.ru'
    html = open(url)
    doc = Nokogiri::HTML(html)
    @posts = []
    doc.css('.binner').each do |post|
      ttl = post.css('h2')
      ttl.children.each { |c| c.remove if c.name == 'span' }
      title = ttl.text.strip.to_s
      description = post.css('.smaincont').text
      img = post.css('.smaincont > div > a')
      img.children.each { |c| c.remove if c.name == 'img' }
      image = ""
      u = ""
      img.each do |n|
        image = n["href"]
      end
      url = post.css('.mlink > span.argmore > a')
      url.each do |el|
        u = el['href']
        puts u
      end
      if title.length > 0
      @posts.push(
        title: title,
        description: description,
        image: image,
        url: u)
      end
    end
    @posts.each do |post|
      if post[:title] != nil
        if @news.length == 0
          News.create({:title => post[:title],:description => post[:description],:image => post[:image], :url =>  post[:url]})
        end
        elsif 
          @news.each do |n|
            n.title != post[:title]
          end
        News.create({:title => post[:title],:description => post[:description],:image => post[:image], :url =>  post[:url]})
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div class="header" id="myHeader">
        <ul class="topnav" id="topNav">
            <li><a href="/" class="logo">ROCKNEWS</a></li>
            <li><%= link_to 'News', news_index_path %></li>
            <li><%= link_to 'Contacts', welcome_contact_us_path %></li>
            <li class="icon"><a href="javascript:void(0);" onclick="toggle()">&#9776;</a></li>
        </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RockNews</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/news/index.html.erb
<div class="container">
    <% @news.each do |n|%>
    <div class="post">
        <h1><%= n.title %></h1>
        <%= image_tag(n.image, class: "post_img") %><br />
        <p><%= n.description %></p>
        <a href="<%= n.url %>" class="button"> Read more </a> 
    </div>
    <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container">
    <div class="post">
        <h1>Welcome to RockNews</h1>
        <p>Rock news is the best site about new in rock sphere. Here you can find fresh information about your favorite groups and singers.
        New albums, rumors, interviwes and plenty of another cool  things you can find here</p>
    </div>
</div>